# Generated by Django 4.1.7 on 2023-03-04 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(blank=True, max_length=1000, unique=True)),
                ('company_name', models.CharField(blank=True, max_length=1000, unique=True)),
                ('location', models.CharField(blank=True, max_length=1000, unique=True)),
                ('job_nature', models.CharField(blank=True, max_length=1000, unique=True)),
                ('job_pay', models.CharField(blank=True, max_length=1000, unique=True)),
                ('joy_currency', models.CharField(blank=True, max_length=1000, unique=True)),
                ('posted', models.CharField(blank=True, max_length=1000, unique=True)),
                ('job_summary', models.CharField(blank=True, max_length=1000, unique=True)),
                ('read_more', models.CharField(blank=True, max_length=1000, unique=True)),
            ],
        ),
    ]
