# Generated by Django 4.1.7 on 2023-03-04 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='company_name',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_nature',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_pay',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_summary',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_title',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='job',
            name='joy_currency',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='job',
            name='posted',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='job',
            name='read_more',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
